apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: helloworldwebapp
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: helloworldwebapp
  spec:
   containers:
   - name: helloworldwebapp
     image: containerdemoregistry1.azurecr.io/helloworldwebapp:v1
     ports:
     - containerPort: 80
   imagePullSecrets:
   - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
 name: helloworldwebapp
spec:
 type: LoadBalancer
 ports:
 - port: 80
 selector:
  app: helloworldwebapp

