trigger:
  - master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: DockerInstaller@0
  displayName:  'Docker Installer'
  inputs:
    dockerVersion: 17.09.0-ce
    releaseType: stable

- script:  docker-compose -f docker-compose.yml -f docker-compose-production.yml up -d
  displayName: 'Build docker image'

