trigger:
  - master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  dockercomposefile: **/docker-compose.yml
  dockercomposeproductionfile: **/docker-compose-production.yml

steps:
- task: DockerInstaller@0
  displayName:  'Docker Installer'
  inputs:
    dockerVersion: 17.09.0-ce
    releaseType: stable

- script:  docker-compose -f $(dockercomposefile) -f $(dockercomposeproductionfile) up -d
  displayName: 'Build docker image'

