trigger:
  - master
  - releases/*

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: DockerCompose@0
  displayName: 'Build docker image'
- script: |
    docker-compose -f docker-compose.yml -f docker-compose-production.yml --project-directory . -p up -d
    docker-compose -f docker-compose.yml -f docker-compose-production.yml --project-directory . down

